cc_library(
    name = "utilities",
    srcs = [
        'utilities.cc',
     ]
)

cc_binary(
    name = "memrm",
    srcs = [
        'memrm.cc',
    ],
    deps = [
        ':utilities',
        '//thirdparty/libmemcached/libmemcachedutil:memcachedutil',
    ]
)

cc_binary(
    name = "memslap",
    srcs = [
        'execute.cc',
        'generator.cc',
        'memslap.cc',
    ],
    deps = [
        ':utilities',
        '//thirdparty/libmemcached/libmemcachedutil:memcachedutil',
    ]
)

cc_binary(
    name = "memparse",
    srcs = [
        'memparse.cc',
    ],
    deps = [
        ':utilities',
        '//thirdparty/libmemcached/libmemcachedutil:memcachedutil',
    ]
)

cc_binary(
    name = "memping",
    srcs = [
        'memping.cc',
    ],
    deps = [
        ':utilities',
        '//thirdparty/libmemcached/libmemcachedutil:memcachedutil',
    ]
)

cc_binary(
    name = "memcp",
    srcs = [
        'memcp.cc',
    ],
    deps = [
        ':utilities',
        '//thirdparty/libmemcached/libmemcachedutil:memcachedutil',
    ]
)

cc_binary(
    name = "memerror",
    srcs = [
        'memerror.cc',
    ],
    deps = [
        ':utilities',
        '//thirdparty/libmemcached/libmemcachedutil:memcachedutil',
    ]
)

cc_binary(
    name = "memdump",
    srcs = [
        'memdump.cc',
    ],
    deps = [
        ':utilities',
        '//thirdparty/libmemcached/libmemcachedutil:memcachedutil',
    ]
)

cc_binary(
    name = "memexist",
    srcs = [
        'memexist.cc',
    ],
    deps = [
        ':utilities',
        '//thirdparty/libmemcached/libmemcachedutil:memcachedutil',
    ]
)

cc_binary(
    name = "memflush",
    srcs = [
        'memflush.cc',
    ],
    deps = [
        ':utilities',
        '//thirdparty/libmemcached/libmemcachedutil:memcachedutil',
    ]
)

cc_binary(
    name = "memstat",
    srcs = [
        'memstat.cc',
    ],
    deps = [
        ':utilities',
        '//thirdparty/libmemcached/libmemcachedutil:memcachedutil',
    ]
)

cc_binary(
    name = "memtouch",
    srcs = [
        'memtouch.cc',
    ],
    deps = [
        ':utilities',
        '//thirdparty/libmemcached/libmemcachedutil:memcachedutil',
    ]
)

cc_binary(
    name = "memcat",
    srcs = [
        'memcat.cc',
    ],
    deps = [
        ':utilities',
        '//thirdparty/libmemcached/libmemcachedutil:memcachedutil',
    ]
)

cc_binary(
    name = "memcapable",
    srcs = [
        'memcapable.cc'
    ],
    deps = [
        ':utilities',
        '//thirdparty/libmemcached/libmemcachedutil:memcachedutil',
    ]
)
