cc_library(
    name = 'lzmadec',
    srcs = [
        'main.c',
	'buffer.c',
	'io.c'
    ],
    deps = [
    ],
	extra_cppflags = [
		'-DHAVE_CONFIG_H',
	],
	incs = [
		'../../',
		'.'
	],
	warning = 'no'
)
