cc_library(
    name = "memcachedprotocol",
    srcs = [
        "ascii_handler.c",
        "binary_handler.c",
        "cache.c",
        "handler.c",
        "pedantic.c",
    ],
    deps = [
        "//thirdparty/libmemcached/libmemcached:memcached",
    ]
)
