cc_library(
    name = 'protobuf',
    deps = '//thirdparty/protobuf-2.3.0/src/google/protobuf:protobuf'
)

cc_library(
    name = 'protoc',
    deps = '//thirdparty/protobuf-2.3.0/src/google/protobuf:protoc'
)

