cc_library(
    name = 'gmock',
    deps = '//thirdparty/gmock-1.6.0:gmock'
)

cc_library(
    name = 'gmock_main',
    deps = '//thirdparty/gmock-1.6.0:gmock_main'
)



cc_library(
    name = 'gmockgtest',
    deps = '//thirdparty/gmock-1.6.0:gmockgtest'
)
