cc_library(
    name = 'double-conversion',
    deps = '//thirdparty/double-conversion-dev:double-conversion'
)

#cc_test(
#    name = 'test-dtoa',
#    srcs = 'test/cctest/test-dtoa.cc',
#    deps = ':double-conversion'
#)

