cc_library(
    name = "memcachedutil",
    srcs = [
        "flush.cc",
        "pid.cc",
        "ping.cc",
        "pool.cc",
        "version.cc",
    ],
    deps = [
        '#pthread',
        '//thirdparty/libmemcached:memcached',
    ],
)
