cc_library(
    name = 'double-conversion',
    srcs = [
        'src/bignum.cc',
        'src/bignum-dtoa.cc',
        'src/cached-powers.cc',
        'src/diy-fp.cc',
        'src/double-conversion.cc',
        'src/fast-dtoa.cc',
        'src/fixed-dtoa.cc',
        'src/strtod.cc'
    ],
    warning = 'no'
)

#cc_test(
#    name = 'test-dtoa',
#    srcs = 'test/cctest/test-dtoa.cc',
#    deps = ':double-conversion'
#)

